version: '2'
services:
  buildbot:
    build: master
    environment:
        - BUILDBOT_CONFIG_DIR=config
        - BUILDBOT_CONFIG_URL=https://raw.githubusercontent.com/dandeliondeathray/niancat-build/master/master/master.cfg
        - BUILDBOT_WORKER_PORT=9989
        - BUILDBOT_WEB_URL=http://rey:8010/
        - WORKERPASS
    ports:
        - "8010:8010"
    volumes:
        - /var/lib/buildbot/db

  worker:
    build: niancat-micro-worker
    environment:
        BUILDMASTER: buildbot
        BUILDMASTER_PORT: 9989
        WORKERNAME: niancat-micro-worker
        WORKERPASS:
        WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    links:
        - buildbot
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /buildbot/data:/buildbot/data
        - /buildbot/ivy2:/home/buildbot/.ivy2
